version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - myNetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - myNetwork

  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - myNetwork
    restart: on-failure
networks:
  myNetwork:
    driver: bridge