swagger: "2.0"
info:
  title: "API Documentation"
  description: "Documentação da API"
  version: "1.0.0"
paths:
  /user:
    post:
      tags:
        - "User"
      summary: "Cria um novo usuário"
      parameters:
        - name: user
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        201:
          description: User created successfully
        401:
          description: Invalid credentials
  /token:
    post:
      tags:
        - "Token"
      summary: "Cria um token para um usuário existente"
      parameters:
        - name: user
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        200:
          description: Token created successfully
        401:
          description: Invalid credentials
  /cep:
    post:
      tags:
        - "CEP"
      summary: "Busca os dados da API do ViaCEP e da API do INPE de previsão do tempo"
      parameters:
        - name: token
          in: formData
          required: true
          type: string
        - name: CEP
          in: formData
          required: true
          type: string
      responses:
        200:
          description: Data fetched successfully
        401:
          description: Invalid credentials
  /logs:
    get:
      tags:
        - "LOG"
      summary: "Busca os logs do usuário específico."
      parameters:
        - name: token
          in: query
          required: true
          type: string
      responses:
        200:
          description: Logs fetched successfully
        401:
          description: Invalid credentials
